# Generated by Django 4.2 on 2023-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=300)),
                ("LastName", models.CharField(max_length=300)),
                ("Email", models.EmailField(max_length=254, verbose_name="")),
            ],
        ),
    ]
