# Generated by Django 4.2 on 2023-04-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="weather_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
