# Generated by Django 4.2 on 2023-04-30 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_weather_user_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather_user",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now, max_length=254, verbose_name=""
            ),
            preserve_default=False,
        ),
    ]
